### ISSUE TITLE
Asking for TBC update

### ISSUE THREAD

**Issue by jpxthu** [marknl/LibEncounters#1]
Thanks!

**Comment by marknl** [comment]
Hi, yes I'll make an update for TBC. Thanks for the suggestion!

**Comment by marknl** [comment]
TBC update released.
https://github.com/marknl/LibEncounters/releases/tag/r2-release
https://www.curseforge.com/wow/addons/libencounters-classic/files/3341301

**Comment by jpxthu** [comment]
Thanks!
